In [50]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

df = pd.read_csv('../data/processed/cleaned_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6607 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6607 non-null   object
 17  Distance_from_Home          6607 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [19]:
level = {'Low': 0, 'Medium': 1, 'High': 2}
ordinal_cols = ['Parental_Involvement', 'Access_to_Resources', 'Motivation_Level', 'Family_Income', 'Teacher_Quality']

for col in ordinal_cols:
    df[col] = df[col].map(level)

edu_mapping = {'High School': 0, 'College': 1, 'Postgraduate': 2}
df['Parental_Education_Level'] = df['Parental_Education_Level'].map(edu_mapping)

df_encoded = pd.get_dummies(df, dtype=int, drop_first=True)

In [23]:
df_encoded.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Sleep_Hours,Previous_Scores,Motivation_Level,Tutoring_Sessions,Family_Income,Teacher_Quality,...,Exam_Score,Extracurricular_Activities_Yes,Internet_Access_Yes,School_Type_Public,Peer_Influence_Neutral,Peer_Influence_Positive,Learning_Disabilities_Yes,Distance_from_Home_Moderate,Distance_from_Home_Near,Gender_Male
0,23,84,0,2,7,73,0,0,0,1,...,67,0,1,1,0,1,0,0,1,1
1,19,64,0,1,8,59,0,2,1,1,...,61,0,1,1,0,0,0,1,0,0
2,24,98,1,1,7,91,1,2,1,1,...,74,1,1,1,1,0,0,0,1,1
3,29,89,0,1,8,98,1,1,1,1,...,71,1,1,1,0,0,0,1,0,1
4,19,92,1,1,6,65,1,3,1,2,...,70,1,1,1,1,0,0,0,1,0

In [25]:
df_encoded.shape

(6607, 22)

In [ ]:
# move Exam_Score to the end of dataframe

move_column = df_encoded.pop('Exam_Score')
df_encoded['Exam_Score'] = move_column

df_encoded

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Sleep_Hours,Previous_Scores,Motivation_Level,Tutoring_Sessions,Family_Income,Teacher_Quality,...,Extracurricular_Activities_Yes,Internet_Access_Yes,School_Type_Public,Peer_Influence_Neutral,Peer_Influence_Positive,Learning_Disabilities_Yes,Distance_from_Home_Moderate,Distance_from_Home_Near,Gender_Male,Exam_Score
0,23,84,0,2,7,73,0,0,0,1,...,0,1,1,0,1,0,0,1,1,67
1,19,64,0,1,8,59,0,2,1,1,...,0,1,1,0,0,0,1,0,0,61
2,24,98,1,1,7,91,1,2,1,1,...,1,1,1,1,0,0,0,1,1,74
3,29,89,0,1,8,98,1,1,1,1,...,1,1,1,0,0,0,1,0,1,71
4,19,92,1,1,6,65,1,3,1,2,...,1,1,1,1,0,0,0,1,0,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,2,1,7,76,1,1,2,1,...,0,1,1,0,1,0,0,1,0,68
6603,23,76,2,1,8,81,1,3,0,2,...,0,1,1,0,1,0,0,1,0,69
6604,20,90,1,0,6,65,0,3,0,1,...,1,1,1,0,0,0,0,1,0,68
6605,10,86,2,2,6,91,2,2,0,1,...,1,1,0,0,1,0,0,0,0,68
6606,15,67,1,0,9,94,1,0,1,1,...,1,1,1,0,1,0,0,1,1,64

In [43]:
X1 = df_encoded.iloc[:,0:21]
X2 = df_encoded.iloc[:,0:21]

In [44]:
X1.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Sleep_Hours,Previous_Scores,Motivation_Level,Tutoring_Sessions,Family_Income,Teacher_Quality,...,Parental_Education_Level,Extracurricular_Activities_Yes,Internet_Access_Yes,School_Type_Public,Peer_Influence_Neutral,Peer_Influence_Positive,Learning_Disabilities_Yes,Distance_from_Home_Moderate,Distance_from_Home_Near,Gender_Male
0,23,84,0,2,7,73,0,0,0,1,...,0,0,1,1,0,1,0,0,1,1
1,19,64,0,1,8,59,0,2,1,1,...,1,0,1,1,0,0,0,1,0,0
2,24,98,1,1,7,91,1,2,1,1,...,2,1,1,1,1,0,0,0,1,1
3,29,89,0,1,8,98,1,1,1,1,...,0,1,1,1,0,0,0,1,0,1
4,19,92,1,1,6,65,1,3,1,2,...,1,1,1,1,1,0,0,0,1,0

In [45]:
X1.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Sleep_Hours', 'Previous_Scores',
       'Motivation_Level', 'Tutoring_Sessions', 'Family_Income',
       'Teacher_Quality', 'Physical_Activity', 'Parental_Education_Level',
       'Extracurricular_Activities_Yes', 'Internet_Access_Yes',
       'School_Type_Public', 'Peer_Influence_Neutral',
       'Peer_Influence_Positive', 'Learning_Disabilities_Yes',
       'Distance_from_Home_Moderate', 'Distance_from_Home_Near',
       'Gender_Male'],
      dtype='object')

In [ ]:
# Standardization

cols = ['Hours_Studied', 'Attendance', 'Parental_Involvement', 'Access_to_Resources', 'Sleep_Hours', 'Previous_Scores', 'Motivation_Level', 'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'Physical_Activity', 'Parental_Education_Level', 'Extracurricular_Activities_Yes', 'Internet_Access_Yes', 'School_Type_Public', 'Peer_Influence_Neutral', 'Peer_Influence_Positive', 'Learning_Disabilities_Yes', 'Distance_from_Home_Moderate', 'Distance_from_Home_Near', 'Gender_Male']

scale_standard = StandardScaler()
X1 = scale_standard.fit_transform(X1)
X1 = pd.DataFrame(X1, columns=cols)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Sleep_Hours,Previous_Scores,Motivation_Level,Tutoring_Sessions,Family_Income,Teacher_Quality,...,Parental_Education_Level,Extracurricular_Activities_Yes,Internet_Access_Yes,School_Type_Public,Peer_Influence_Neutral,Peer_Influence_Positive,Learning_Disabilities_Yes,Distance_from_Home_Moderate,Distance_from_Home_Near,Gender_Male
count,6607.000,6607.000,6607.000,6607.000,6607.000,6607.000,6607.000,6607.000,6607.000,6607.000,...,6607.000,6607.000,6607.000,6607.000,6607.000,6607.000,6607.000,6607.000,6607.00,6607.000
mean,0.000,-0.000,0.000,0.000,-0.000,-0.000,0.000,0.000,0.000,0.000,...,-0.000,0.000,-0.000,0.000,-0.000,-0.000,0.000,0.000,0.00,0.000
std,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.00,1.000
min,-3.168,-1.730,-1.562,-1.576,-2.063,-1.741,-1.303,-1.214,-1.061,-2.003,...,-0.894,-1.215,-3.499,-1.513,-0.803,-0.815,-0.343,-0.658,-1.22,-1.169
25%,-0.664,-0.864,-0.124,-0.143,-0.701,-0.838,-1.303,-0.401,-1.061,-0.327,...,-0.894,-1.215,0.286,-1.513,-0.803,-0.815,-0.343,-0.658,-1.22,-1.169
50%,0.004,0.002,-0.124,-0.143,-0.020,-0.005,0.134,-0.401,0.286,-0.327,...,-0.894,0.823,0.286,0.661,-0.803,-0.815,-0.343,-0.658,0.82,0.856
75%,0.672,0.868,1.314,1.289,0.661,0.898,0.134,0.411,0.286,1.349,...,0.390,0.823,0.286,0.661,1.245,1.227,-0.343,1.519,0.82,0.856
max,4.011,1.734,1.314,1.289,2.024,1.731,1.572,5.288,1.633,1.349,...,1.674,0.823,0.286,0.661,1.245,1.227,2.917,1.519,0.82,0.856

In [57]:
# Normalization

scal_min_max = MinMaxScaler(feature_range=(0,1))
X2 = scal_min_max.fit_transform(X2)
X2 = pd.DataFrame(X2, columns=cols)

X2.describe()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Sleep_Hours,Previous_Scores,Motivation_Level,Tutoring_Sessions,Family_Income,Teacher_Quality,...,Parental_Education_Level,Extracurricular_Activities_Yes,Internet_Access_Yes,School_Type_Public,Peer_Influence_Neutral,Peer_Influence_Positive,Learning_Disabilities_Yes,Distance_from_Home_Moderate,Distance_from_Home_Near,Gender_Male
count,6607.000000,6607.000000,6607.000000,6607.000000,6607.000000,6607.000000,6607.000000,6607.000000,6607.000000,6607.000000,...,6607.000000,6607.000000,6607.000000,6607.000000,6607.000000,6607.000000,6607.000000,6607.000000,6607.000000,6607.000000
mean,0.441287,0.499436,0.543212,0.550098,0.504843,0.501411,0.453231,0.186715,0.393825,0.597624,...,0.348040,0.596035,0.924474,0.695929,0.392311,0.399273,0.105191,0.302407,0.598002,0.577267
std,0.139316,0.288687,0.347761,0.349173,0.244687,0.287996,0.347899,0.153821,0.371308,0.298354,...,0.389448,0.490728,0.264258,0.460048,0.488302,0.489786,0.306823,0.459335,0.490339,0.494031
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.348837,0.250000,0.500000,0.500000,0.333333,0.260000,0.000000,0.125000,0.000000,0.500000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.441860,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.125000,0.500000,0.500000,...,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
75%,0.534884,0.750000,1.000000,1.000000,0.666667,0.760000,0.500000,0.250000,0.500000,1.000000,...,0.500000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000